version: '3'

networks:
  rabbit-network:
  mongo-network:


volumes:
  rabbitmq_data:
  mongodb_data_container:


services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/bitnami
    ports:
      - 15672:15672
    networks:
      - rabbit-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped


  userscripts:
    build: .
    container_name: userscripts
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - rabbit-network
      - mongo-network
    ports:
      - 8080:80
      - 3000:3000
    environment:
      - AMQP_USER=${RABBITMQ_USERNAME}
      - AMQP_PASS=${RABBITMQ_PASSWORD}
      - AMQP_URI=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mongo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
